services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: app
    command: npm run start:prod
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=3000
